# -*- coding: utf-8 -*-
"""if/else.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1URzvVb87xJrnWoUel-CCXPk53WSL-4Gk

Exemplo de como deve ser feito
"""

a ="Digite o  input(primeiro numero ")
b = input("Digite o segundo numero ")
if b > a:
  print (b)
elif b == a:
  print("Os numeros são iguais")
else:
  print (a)

"""Exercio"""

numero = int (input("Digite o valor "))
if  numero > 0:
   print ("Positivo")
elif numero == 0:
   print ("Valr igual")
else:
   print ("negativo")

sexo = input("Digite F ou M ")
if sexo == "F" or sexo == "f":
  print ("Sexo Feminino")
elif sexo == "M" or sexo == "m":
  print ("Sexo Masculino")
else:
  print ("Sexo Invalido")

letra = input("Digite uma letra ")
if letra == "a" or letra == "e" or letra =="i" or letra =="o" or letra =="u" or letra == "A" or letra == "E" or letra == "I" or letra == "O" or letra == "U":
  print("É uma vogal")
else:
  print("É uam consoante")

Parcial1 = float (input("Insira a primeira nota "))
Parcial2 = float (input("Insira a segunda nota "))
media = (Parcial1 + Parcial2)/2
if media == 10:
  print("Aprovado com distinção")
elif media >= 7:
  print("Aprovado")
else:
  print("Reprovado")

a = int (input("Insira o primeiro numero "))
b = int (input("Insira o segundo numero "))
c = int (input("Insira o terceiro numero "))
if a > b and a > c:
 print("a" , a)
elif b > a and b > c:
 print("b" , b)
else:
  print("c" , c)

a = int (input("Insira o primeiro numero "))
b = int (input("Insira o segundo numero "))
c = int (input("Insira o terceiro numero "))
if a > b and a > c:
 print("Maior a" , a)
elif b > a and b > c:
 print("Maior b" , b)
elif c > c and c > b:
  print("Maior c" , c)
if a < b and a < c:
 print("Menor a" , a)
elif b < a and b < c:
 print("Menor b" , b)
else:
  print("Menor c" , c)

a = float (input("Insira o valor do primeiro produto "))
b = float (input("Insira o valor do segundo produto "))
c = float (input("Insira o valor do terceiro produto "))
if a < b and a < c:
  print("a Produto com menor preço" , a)
elif b < a and b < c:
  print("b Produto com menor preço" , b)
else:
  print("c Produto com menor preço", c)

a = int (input("Insira o primeiro numero "))
b = int (input("Insira o segundo numero "))
c = int (input("Insira o terceiro numero "))
if a > b and a > c and b > c:
 print("a , b , c")
elif b > a and b > c and c > a:
 print("b , c , a")
elif c > a and c > b and b > a:
 print("c , b , a")
elif a > b and a > c and b < c:
 print("a , c , b")
elif b > a and b > c and c < a:
 print("b, a , c")
elif c > a and c > b and b < a:
 print("c, a , b")

a = input("Digite o turno de estudo: M (Matutino) V (Vespertino) N (Notrno) ")
if a == "m" or a == "M":
 print("Bom dia")
elif a == "v" or a == "V":
  print("Boa tarde")
elif a == "n" or a == "N":
  print("Boa noite")
else:
  print("Valor invalido")

num1 = int (input("Insira o primeiro numero "))
num2 = int (input("Insira o segundo numero "))
if num1 > num2:
 print("Maior num1" , num1 , "Menor num2" , num2)
else:
  print("Maior num2" , num2 , "Menor num1" , num1)

data = int (input("Digite o numero de acordo com o dia da semana "))
if data == 1:
 print("Domingo")
elif data == 2:
 print("Segunda - feira")
elif data == 3:
 print("Terça - feira")
elif data == 4:
 print("Quarta - feira")
elif data == 5:
 print("Quinta - feira")
elif data == 6:
 print("Sexta - feira")
elif data == 7:
 print("Sabado")